### ISSUE TITLE
UI Feature Request: Provide feedback that tests are running

### ISSUE THREAD

**Issue by jfsiii** [developit/esbench#1]
Currently, when you click the "Run" button, there's no indication the tests are running. 

Two suggestions:
1. Disable the "Run" button
2. Put loading animation or text "running..." in test row while test is active/running

**Comment by developit** [comment]
Hey John,

This is something I'm working on, should have a fix up soon.  The feedback is actually there, but the test runner never gives the UI enough time to update (it's using preact so updates are debounced via `rAF`).  Interestingly, if you have async tests, progress is shown properly for them (see [example test](http://www.esbench.com/bench/55d4d44e2efbca1100bf7251)).

Will keep this issue updated with progress on fixing the running indicator for synchronous tests.

_Edit:_ here's what it looks like:
![preview](https://i.gyazo.com/497da2a25208bb4fe6705f21890de59c.gif)

**Comment by jfsiii** [comment]
Oh, great. That's exactly what I'd expect.

**Comment by developit** [comment]
My gif recording cut out before it showed the graph, but it animates in too. :palm_tree:

**Comment by jfsiii** [comment]
No problem, I saw it in the async test you linked. Nice one.

**Comment by developit** [comment]
Closing for now since the latest update at least greys out the button. I'm still working on addressing some very weird async issues with [Benchmark.js](http://benchmarkjs.com).
