### ISSUE TITLE
Add option to run es6 without compiling it with Babel.

### ISSUE THREAD

**Issue by NoNameProvided** [developit/esbench#2]
I think it's a pretty common user scenario when someone want to test the performance diff between a new ES2015 function and it's es5 equivalent. Now this kind of perf test is impossible because ES2015 code is compiled into es5 with Babel.

It would be nice to have a checkbox or something at every test to turn on/off Babel compilation for that given test.

**Comment by developit** [comment]
That's a good idea!  I'm not sure how to make the setting per-test (like the async setting), but it'd be super easy to do it for a given suite.

**Comment by NoNameProvided** [comment]
Well it's a good first step to add it as a suite option.

**Comment by NoNameProvided** [comment]
Do you have any ETA for this or about the open sourcing of the project?

**Comment by developit** [comment]
@NoNameProvided Sorry for the lag there, I just deployed the transpile option. I was actually able to do it for both the suite and each test. I also fix the SSL issue.

<img width="174" src="https://cloud.githubusercontent.com/assets/105127/17109114/9b6680ac-5264-11e6-974b-25a5f13ed16e.png">

<img width="645" src="https://cloud.githubusercontent.com/assets/105127/17109113/9b63c92a-5264-11e6-9076-ce3dd3055372.png">

**Comment by NoNameProvided** [comment]
Thanks!
