### ISSUE TITLE
Edit Test Name, can't backspace all the way.

### ISSUE THREAD

**Issue by MobiusHorizons** [developit/esbench#6]
First let me say that this is a very nice tool, thanks for building it!!

I noticed that when editing the test name, if you backspace all the characters, it gets overwritten by the default name. This appears to be because of `bench.js:301`

```
let name = test.name || `Test ${i+1}`; 
```

I suspect this behavior could be fixed by changing that line to 

```
let name = (test.name != null) ? test.name : `Test ${i+1}`;
```

Screencast : http://screencast.com/t/THbhBARYJAt

**Comment by developit** [comment]
Ah yup, one of my long-standing annoyances I've meant to fix haha. Your solution seems pretty simple I might throw this in for now until I refactor the editor view.  Likely going with cleaner tabs and a more IDE-like feel.

**Comment by MobiusHorizons** [comment]
Cool, keep me posted :)

**Comment by developit** [comment]
Fixed April 2020
