### ISSUE TITLE
[Feature Request] Delete tests from bench

### ISSUE THREAD

**Issue by jfsiii** [developit/esbench#7]
See https://esbench.com/bench/58cad06499634800a0347a72 for an example.

Leaving this test in throws off the results.

<img width="584" alt="screen shot 2017-03-19 at 2 00 57 pm" src="https://cloud.githubusercontent.com/assets/57655/24084742/42c870fa-0cad-11e7-9fa3-890e2279199d.png">

**Comment by developit** [comment]
indeed indeed. right now it's only possible via the API.

**Comment by jfsiii** [comment]
Is that something one could do, say, from Dev Tools console? I don't mind doing that until UI support lands.

**Comment by developit** [comment]
totally! on your bench:

```js
// grab a reference to the page component:
var comp = document.getElementById('view-bench')._component;

// delete bench at index 4:
comp.state.bench.tests.splice(4, 1);

// persist it and save to the API:
comp.setState({ });
comp.save();
```

**Comment by developit** [comment]
Fixed April 2020
